In [1]:
import numpy as np
import dg

In [2]:
x_tsr = np.arange(4).reshape([2,2,1])
w_tsr = np.arange(6).reshape([3,2])

In [3]:
x = dg.identity(x_tsr)
w = dg.identity(w_tsr)

In [4]:
y = dg.mat_mul(w, x)

In [5]:
print('x dimensions:')
print(x.body.output.data)
print(x.body.output.data.shape)
print(x.body.output.grad)

print('w dimensions:')
print(w.body.output.data)
print(w.body.output.data.shape)
print(w.body.output.grad)

print('y dimensions:')
print(y.body.output.data)
print(y.body.output.data.shape)
print(y.body.output.grad)

x dimensions:
[[[0]
  [1]]

 [[2]
  [3]]]
(2, 2, 1)
[[[0.]
  [0.]]

 [[0.]
  [0.]]]
w dimensions:
[[0 1]
 [2 3]
 [4 5]]
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
y dimensions:
[[[ 1]
  [ 3]
  [ 5]]

 [[ 3]
  [13]
  [23]]]
(2, 3, 1)
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]


In [6]:
y.body.output.grad

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [7]:
y.body.output.grad = y.body.output.grad + 1

In [8]:
y.body.backward()

In [9]:
x.body.output.grad

array([[[6.],
        [9.]],

       [[6.],
        [9.]]])

In [10]:
w.body.output.grad

array([[2., 4.],
       [2., 4.],
       [2., 4.]])

In [11]:
y_label = np.array([[2,4, 6],[4,14, 24]])

In [12]:
y_label = y_label.reshape([2,3,1])
y_label = dg.identity(y_label)

In [13]:
loss = dg.mse(y_label, y)

In [14]:
y_label

In [15]:
y.__str__()

'<dg.core.OperatorNode object at 0x7fceddfe1c50>'

In [16]:
loss.prev

In [17]:
loss.body.output.data

1.0

In [18]:
y.body.output.data

array([[[ 1],
        [ 3],
        [ 5]],

       [[ 3],
        [13],
        [23]]])

In [19]:
y_label.body.output.data

array([[[ 2],
        [ 4],
        [ 6]],

       [[ 4],
        [14],
        [24]]])

In [20]:
loss.body.backward()

In [21]:
loss.body.output.grad

array(0.)